### ISSUE TITLE
is there a way that i can select minutes too ?

### ISSUE THREAD

**Issue by sagarrs** [logisticinfotech/react-native-datetimepicker#3]
I am able to select time using this param onTimeSelected={this.onTimeSelected}, is there any way that i can display the minutes in the multiples of 5 and select the minutes, i hope there is a way
Thanks.

**Comment by nileshkikani** [comment]
Yes, There is the props 'timeStep' in which you have to pass the minute. For ex., if you will pass the 60 then time will show every 60 minutes. if you want every 5 minute then you have to pass 5 in that props.
