### ISSUE TITLE
I am getting the following warnings even though i am using the correct methods

### ISSUE THREAD

**Issue by sagarrs** [logisticinfotech/react-native-datetimepicker#4]
![Screenshot 2019-10-27 at 12 11 17 PM](https://user-images.githubusercontent.com/17675875/67630792-3267ab00-f8b3-11e9-8200-0ccd6d298ec4.png)

here's the code i have written

    export default class CustomDatePicker extends Component {
      constructor(props) {
        super(props);
        this.state = {
          date1: '',
          time1: '',
          dateTime1: '',
          date2: '',
          time2: '',
          dateTime2: '',
          date3: '',
          time3: '',
          dateTime3: '',
        };
      }

      onDateSelected = date => {
        // setTimeout(()=>{}, 5000);
        this.setState({
          date1: date,
          date2: moment(date, 'DD-MM-YYYY').format('DD MMM YYYY'),
          date3: moment(date, 'DD-MM-YYYY').format('Do MMMM YYYY'),
        });
      };

      onTimeSelected = time => {
        this.setState({
          time1: time,
          time2: moment(time, 'hh:mm a').format('HH:mm'),
          time3: moment(time, 'hh:mm a').format('HH:mm a'),
        });
      };

      onDateTimeSelected = datetime => {
        // format="MMMM Do YYYY, h:mm:ss a"
        this.setState({
          dateTime1: datetime.datetime,
          dateTime2: moment(datetime.datetime, 'DD-MM-YYYY hh:mm a').format('DD MMM YYYY 
HH:mm'),
          dateTime3: moment(datetime.datetime, 'DD-MM-YYYY hh:mm a').format('MMMM Do YYYY, h:mm:ss a'),
            });
          };
      render() {
        const { date1, date2, date3, time1, time2, time3, dateTime1, dateTime2, dateTime3 } = 
        this.state;
            return (
              <ScrollView>
                <SafeAreaView style={styles.container}>
                  <HorizontalDatePicker
                    datePickerContainerStyle={{backgroundColor: 'white'}}
                    timePickerContainerStyle={{backgroundColor: 'white'}}
                    yearContainerStyle={{backgroundColor: 'white'}}
                    yearTextStyle={{color: '#31588A', paddingLeft: 200}}
                    unSelectedTextStyle={[{color: '#31588A'}]}
                    selectedTextStyle={{color: '#EACF79'}}
                    onDateSelected={this.onDateSelected}
                    onTimeSelected={this.onTimeSelected}
                    onDateTimeSelected={this.onDateTimeSelected}
                  />
                <View style={styles.gapStyle} />
                    <View style={styles.displayContainer}>
                       <Text style={[styles.instructions, styles.textColor1]}>{date1}</Text>
                       <Text style={[styles.instructions, styles.textColor1]}>{time1}</Text>
                       <Text style={[styles.instructions, styles.textColor1]}>{dateTime1}</Text>
               </View>
              <View style={styles.displayContainer}>
                    <Text style={[styles.instructions, styles.textColor2]}>{date2}</Text>
                    <Text style={[styles.instructions, styles.textColor2]}>{time2}</Text>
                    <Text style={[styles.instructions, styles.textColor2]}>{dateTime3}</Text>
              </View>
              <View style={styles.displayContainer}>
                    <Text style={[styles.instructions, styles.textColor3]}>{date3}</Text>
                    <Text style={[styles.instructions, styles.textColor3]}>{time3}</Text>
                    <Text style={[styles.instructions, styles.textColor3]}>{dateTime3}</Text>
              </View>
               </SafeAreaView>
            </ScrollView>
          );
      }
    }

**Comment by nileshkikani** [comment]
Solve in 1.0.16
